apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stg-deployment
  namespace: nginx-stg
  labels:
    app: nginx
    env: stg
    team: infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: stg
      team: infra

  template:
    metadata:
      labels:
        app: nginx
        env: stg
        team: infra
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "100m"