---
apiVersion: v1
kind: Namespace
metadata: 
  name: nginx-dev
  labels:
    app: nginx
    env: dev
    team: infra

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-nginx-dev
  namespace: nginx-dev  
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: "400Mi"
    limits.cpu: "400m"
    limits.memory: "400Mi"