---
apiVersion: v1
kind: Namespace
metadata: 
  name: app1-namespace
  labels:
    name: app1-namespace
    app: app1
    env: dev 

---
apiVersion: v1
kind: ResourceQuota
metadata: 
  name: quota-app1-namespace
  namespace: app1-namespace
spec:
  hard:
    requests.cpu: "800m"
    requests.memory: "800Mi"
    limits.cpu: "800m"
    limits.memory: "800Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1-namespace
  labels:
    app: app1
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:                              # Pod Template
    metadata:
      labels:
        name: app1
        app: app1
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "200m"
