---
apiVersion: v1
kind: Namespace
metadata: 
  name: apache-stg
  labels:
    app: apache
    env: dev
    team: infra

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-apache-dev
  namespace: apache-stg
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: "400Mi"
    limits.cpu: "400m"
    limits.memory: "400Mi"